import {ArrowUpRight} from 'lucide-react';
export default function Home(){return <main id="main">
<section className="assessment-hero wrap"><div><p className="eyebrow">MAPLE BRIDGE THERAPY · CAIRO</p><h1>Understand what’s<br/>getting in the way.<br/><em>Know what to do next.</em></h1><p className="lead">Comprehensive pediatric occupational therapy assessments for families seeking clarity about their child’s everyday life.</p><p>Canadian-trained OTs. Individualized assessment. Home and play observation. A practical Participation Plan.</p><div className="assessment-actions"><a className="button" href="/assessment">Explore the Comprehensive Assessment <ArrowUpRight size={18}/></a><a className="text-link" href="/contact?service=Clarity%20Consultation">Book a Clarity Consultation ↗</a></div></div><figure><img src="/images/hero-play.jpg" alt="A child exploring movement and play in a warm, sunlit space" width="1536" height="1024" fetchPriority="high"/><figcaption>Understanding children in the context of everyday life.</figcaption></figure></section>
<div className="quiet-credentials wrap"><span>Canadian-trained, MSc-qualified OTs</span><span>12+ years combined experience</span><span>Founder-led, family-centred care</span></div>
<section className="wrap assessment-section parent-section"><div><p className="eyebrow">WHEN YOU WANT A CLEARER PICTURE</p><h2>You know your child is capable.<br/><em>But something is getting in the way.</em></h2></div><div><ul className="parent-questions"><li>They understand the work but struggle to get it onto paper.</li><li>Homework and everyday routines need constant prompting.</li><li>Movement feels difficult, or ordinary demands become overwhelming.</li><li>You’ve heard concerns, but still don’t have a clear explanation.</li></ul><p>Understanding what is happening helps us decide what support will be useful.</p></div></section>
<section className="flagship-section"><div className="wrap assessment-section"><p className="eyebrow">OUR FLAGSHIP SERVICE</p><h2>Comprehensive<br/><em>Participation Assessment</em></h2><p className="section-intro">What is helping or getting in the way of your child participating in everyday life—and what should we do about it?</p><ol className="journey-grid">{[['Listen','Your concerns, your child’s strengths, and the questions that matter.'],['Assess','Individualized assessment and relevant school information supplied by you.'],['Observe','Home and natural play observation to understand everyday demands.'],['Understand','Findings connected through clinical reasoning, explained in plain English.'],['Plan','A written report, 3–5 priorities, and a parent strategy session.'],['Review','One follow-up around 4–6 weeks later to review progress and next steps.']].map(([t,d],i)=><li key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></li>)}</ol><a className="button" href="/assessment">See what’s included <ArrowUpRight size={18}/></a></div></section>
<section className="wrap assessment-section"><p className="eyebrow">MORE THAN A TEST SCORE</p><h2>Children live in the real world.<br/><em>Our assessment starts there.</em></h2><div className="difference-grid">{[['Individualized','We select tools around your child and your questions.'],['Real-life','Home and play observation connect the child, the task, and the environment.'],['Interpreted','We explain what findings mean for everyday participation.'],['Actionable','Your Participation Plan sets clear priorities and ways to measure change.']].map(([t,d])=><article key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="framework-band"><div className="wrap"><p className="eyebrow">OUR APPROACH</p><h2>Clarity <span>→</span> Participation <span>→</span> Change</h2><p>Understand what may be getting in the way. Identify what matters. Put a practical, measurable plan into everyday life.</p><a className="text-link" href="/approach">Explore our approach ↗</a></div></section>
<section className="wrap assessment-section parent-section"><h2>Canadian-trained.<br/>Internationally experienced.<br/><em>Focused on real life.</em></h2><div><p>We are two MSc-qualified occupational therapists with more than 12 years of combined experience across pediatric, healthcare, education, and community settings.</p><p>We bring evidence-informed clinical reasoning and multidisciplinary experience to private family care in Cairo.</p><a className="text-link" href="/about">About Maple Bridge Therapy ↗</a></div></section>
<section className="closing-cta"><div className="wrap"><p className="eyebrow">A CLEAR NEXT STEP</p><h2>Tell us what<br/><em>you’re noticing.</em></h2><p>We’ll help determine the appropriate assessment pathway for your child.</p><a className="button" href="/contact">Start with an enquiry <ArrowUpRight size={18}/></a></div></section></main>}
