import {ArrowUpRight} from 'lucide-react';
export const metadata={title:'Occupational Therapy Assessment',description:'Individualized pediatric occupational therapy assessment in Cairo, with home observation, a Participation Plan, parent strategy session, and follow-up.'};
const stages=[
['Pre-assessment review','We review your priorities, developmental and medical history, previous reports, current supports, and relevant work samples.'],
['Parent clinical consultation','Around 60–75 minutes to understand routines, strengths, challenges, and what matters to your family. Together, we identify 3–5 key participation questions.'],
['Individualized child assessment','Around 90–120 minutes, depending on age and need. We explore relevant areas such as movement, coordination, written output, regulation, attention, planning, or self-care. Standardized tools are selected where indicated; every child does not receive the same tests.'],
['Home and natural play observation','Included in the Occupational Therapy Assessment. Observing familiar activities helps us understand the interaction between your child, the task, and their environment—from play and transitions to homework and daily routines.'],
['School Context Review','We consider information you provide: teacher comments, report cards, work samples, SEND/IEP documents, previous assessments, and relevant questionnaires. This does not include school visits or direct teacher consultation.'],
['Clinical interpretation and report','We bring together parent concerns, strengths, test findings, observation, and context to explain what may be affecting participation. A concise written report includes an executive summary, findings, and your child’s Participation Plan.'],
['Results and strategy session','Around 60–75 minutes to explain findings, agree priorities, and work through practical next steps. We clarify what parents can implement, where skilled OT may help, and whether another professional is appropriate.'],
['Follow-up and review','One review of around 30 minutes, approximately 4–6 weeks later. We discuss what was implemented, what changed, remaining barriers, and whether the plan needs adjustment.']
];
const faqs=[
['Does my child need a diagnosis?','No. You can enquire because everyday activities are difficult or because you want to understand concerns more clearly. We first discuss whether this assessment fits your child’s needs.'],
['Which assessments will you use?','We choose tools according to the clinical questions, your child’s age, and their needs. Assessment may explore motor and visual-motor skills, written output, sensory processing, regulation, executive functioning, or everyday independence. We explain the proposed approach before proceeding.'],
['How long does the process take?','The process involves several appointments and time for analysis and reporting. We confirm the schedule and report timeframe before booking. The included follow-up takes place approximately 4–6 weeks after the results and strategy session.'],
['Do you diagnose autism or ADHD?','This is an occupational therapy functional and participation assessment, not an autism, ADHD, learning disorder, or psychiatric diagnostic assessment. Where further diagnostic evaluation may be helpful, we recommend an appropriately qualified professional.'],
['Do you visit schools?','We do not currently offer school visits, teacher consultation packages, or direct school consulting. We incorporate school context through information your family provides.'],
['What school information should I provide?','Relevant teacher comments, reports, handwriting or other work samples, SEND/IEP documents, previous assessments, and school correspondence can help. We will guide you on what is useful for your child’s questions.'],
['Where do home observations take place?','In your child’s familiar home or natural play environment, as agreed before booking. This observation is included in the flagship assessment, not in a Clarity Consultation.'],
['Do you travel across Cairo?','Home-based observation is included within our core service area. For locations requiring extended travel, a fixed travel supplement or arranged private transport may apply. Travel requirements are confirmed before booking.'],
['What happens after the assessment?','You receive a Participation Plan and strategy session, followed by the included review. Next steps may be independent family implementation, parent support, a focused OT package, or referral to another professional.'],
['Does every child need ongoing OT afterward?','No. Recommendations depend on the findings and your priorities. Some families can continue independently; others may benefit from a defined block of skilled support with an outcome review.'],
['Can you work with our existing therapists?','Tell us about current care when you enquire. With your consent, we can discuss whether coordination with an existing therapist is appropriate and agree its scope before proceeding.'],
['What ages do you assess?','Please share your child’s age and main concerns. We confirm suitability and available assessment tools before booking rather than assume every assessment is appropriate for every age.']
];
export default function Assessment(){return <main id="main"><section className="page-hero"><div className="wrap"><p className="eyebrow">OUR FLAGSHIP SERVICE · CAIRO</p><h1>Occupational Therapy<br/><em>Assessment</em></h1><p className="lead">A deeper understanding of your child. Clear priorities. A practical plan for everyday life.</p><a className="button" href="/contact?service=Occupational%20Therapy%20Assessment">Enquire about an assessment <ArrowUpRight size={18}/></a></div></section>
<section className="wrap assessment-section parent-section"><h2>For families looking<br/><em>for an explanation.</em></h2><div><p>When learning, play, movement, routines, or self-care feel harder than expected, an assessment can help clarify what may be contributing.</p><p>We ask: what helps your child participate, what gets in the way, and what should change? The focus is everyday function, strengths, and meaningful priorities.</p><a href="#included" className="text-link">Explore the assessment process ↓</a></div></section>
<section className="flagship-section" id="included"><div className="wrap assessment-section"><p className="eyebrow">WHAT’S INCLUDED</p><h2>A clear process.<br/><em>A connected picture.</em></h2><div className="assessment-stages">{stages.map(([t,d],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section className="wrap assessment-section" id="participation-plan"><p className="eyebrow">YOUR TAKE-HOME ROADMAP</p><h2>Your Child’s<br/><em>Participation Plan</em></h2><p className="section-intro">Around 3–5 priorities, chosen for their importance to your family. For each one, we explain:</p><div className="plan-grid">{[['The goal','Which meaningful activity should improve?'],['The explanation','What child, task, or environmental factors may be contributing?'],['The change','Which practical strategies or adaptations can help?'],['The people','Who can implement each part of the plan?'],['The outcome','How will we know if everyday participation is improving?']].map(([t,d])=><article key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="framework-band"><div className="wrap"><h2>Understanding is the beginning.<br/><em>Implementation brings it into life.</em></h2><p>A written report and strategy session help you understand the findings. The included review helps us learn what is working and decide what comes next.</p></div></section>
<section className="wrap assessment-section"><p className="eyebrow">OTHER WAYS TO BEGIN OR CONTINUE</p><div className="support-grid"><article id="clarity"><h3>Clarity Consultation</h3><p>A parent-focused conversation of around 45–60 minutes to explore concerns, relevant history, whether OT is appropriate, and possible next steps.</p><p className="fine-print">This is not a comprehensive assessment and does not provide formal clinical conclusions. Home observation is not included.</p><a className="text-link" href="/contact?service=Clarity%20Consultation">Enquire about a consultation ↗</a></article><article id="implementation"><h3>Focused Implementation Packages</h3><p>After assessment, where skilled intervention is warranted: a defined goal, baseline, focused intervention, everyday implementation, and an outcome review. Blocks may span 4, 6, or 8 weeks, as agreed.</p></article><article id="review"><h3>Participation Review</h3><p>A defined review to assess progress, adjust the plan, and determine whether support should continue, change, or end.</p></article></div></section>
<section className="wrap assessment-section faq-section"><p className="eyebrow">YOUR QUESTIONS</p><h2>Before you book.</h2>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
<section className="closing-cta"><div className="wrap"><h2>Start with<br/><em>what matters to your family.</em></h2><p>Contact us for current assessment availability and fees.</p><a href="/contact?service=Occupational%20Therapy%20Assessment" className="button">Start an enquiry <ArrowUpRight size={18}/></a></div></section></main>}
